CITIES: list[tuple[str, str]] = [
    ("Mexico City", "Ciudad de México"),
    ("Tijuana", "Baja California"),
    ("Ecatepec", "Estado de México"),
    ("León", "Guanajuato"),
    ("Puebla", "Puebla"),
    ("Ciudad Juárez", "Chihuahua"),
    ("Guadalajara", "Jalisco"),
    ("Monterrey", "Nuevo León"),
    ("Nezahualcóyotl", "Estado de México"),
    ("Zapopan", "Jalisco"),
    ("Chihuahua", "Chihuahua"),
    ("Mérida", "Yucatán"),
    ("Naucalpan", "Estado de México"),
    ("Cancún", "Quintana Roo"),
    ("Saltillo", "Coahuila"),
    ("Aguascalientes", "Aguascalientes"),
    ("Hermosillo", "Sonora"),
    ("Mexicali", "Baja California"),
    ("San Luis Potosí", "San Luis Potosí"),
    ("Culiacán", "Sinaloa"),
    ("Querétaro", "Querétaro"),
    ("Morelia", "Michoacán"),
    ("Chimalhuacán", "Estado de México"),
    ("Reynosa", "Tamaulipas"),
    ("Torreón", "Coahuila"),
    ("Tlalnepantla", "Estado de México"),
    ("Acapulco", "Guerrero"),
    ("Tlaquepaque", "Jalisco"),
    ("Guadalupe", "Nuevo León"),
    ("Durango", "Durango"),
    ("Tuxtla Gutiérrez", "Chiapas"),
    ("Cuautitlán Izcalli", "Estado de México"),
    ("Veracruz", "Veracruz"),
    ("Ciudad Apodaca", "Nuevo León"),
    ("Ciudad López Mateos", "Estado de México"),
    ("Matamoros", "Tamaulipas"),
    ("General Escobedo", "Nuevo León"),
    ("Irapuato", "Guanajuato"),
    ("Xalapa", "Veracruz"),
    ("Tonalá", "Jalisco"),
    ("Mazatlán", "Sinaloa"),
    ("Nuevo Laredo", "Tamaulipas"),
    ("San Nicolás de los Garza", "Nuevo León"),
    ("Ojo de Agua", "Estado de México"),
    ("Valle de Chalco", "Estado de México"),
    ("Celaya", "Guanajuato"),
    ("Tepic", "Nayarit"),
    ("Ixtapaluca", "Estado de México"),
    ("Cuernavaca", "Morelos"),
    ("Villahermosa", "Tabasco"),
    ("Ciudad Victoria", "Tamaulipas"),
    ("Ensenada", "Baja California"),
    ("Ciudad Obregón", "Sonora"),
    ("Nicolás Romero", "Estado de México"),
    ("Soledad de Graciano Sánchez", "San Luis Potosí"),
    ("Ciudad Benito Juárez", "Nuevo León"),
    ("Playa del Carmen", "Quintana Roo"),
    ("Santa Catarina", "Nuevo León"),
    ("Gómez Palacio", "Durango"),
    ("Uruapan", "Michoacán"),
    ("Los Mochis", "Sinaloa"),
    ("Pachuca", "Hidalgo"),
    ("Tampico", "Tamaulipas"),
    ("Tehuacán", "Puebla"),
    ("San Francisco Coacalco", "Estado de México"),
    ("Nogales", "Sonora"),
    ("Oaxaca de Juárez", "Oaxaca"),
    ("La Paz", "Baja California Sur"),
    ("Campeche", "Campeche"),
    ("Monclova", "Coahuila"),
    ("García", "Nuevo León"),
    ("Chilpancingo", "Guerrero"),
    ("Puerto Vallarta", "Jalisco"),
    ("Toluca", "Estado de México"),
    ("Tapachula", "Chiapas"),
    ("Buenavista", "Estado de México"),
    ("Coatzacoalcos", "Veracruz"),
    ("Ciudad Madero", "Tamaulipas"),
    ("Cabo San Lucas", "Baja California Sur"),
    ("Chicoloapan", "Estado de México"),
    ("Ciudad del Carmen", "Campeche"),
    ("San Cristóbal de las Casas", "Chiapas"),
    ("Poza Rica", "Veracruz"),
    ("San Juan del Río", "Querétaro"),
    ("San Luis Río Colorado", "Sonora"),
    ("Chalco", "Estado de México"),
    ("Jiutepec", "Morelos"),
    ("Piedras Negras", "Coahuila"),
    ("Guadalupe", "Zacatecas"),
    ("Chetumal", "Quintana Roo"),
    ("Miramar", "Tamaulipas"),
    ("Salamanca", "Guanajuato"),
    ("Ciudad Acuña", "Coahuila"),
    ("Manzanillo", "Colima"),
    ("San Pablo de las Salinas", "Estado de México"),
    ("Cuautla", "Morelos"),
    ("Zamora", "Michoacán"),
    ("Minatitlán", "Veracruz"),
    ("Villa de Álvarez", "Colima"),
    ("Colima", "Colima"),
]

STATES = [
    "Aguascalientes",
    "Baja California",
    "Baja California Sur",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Ciudad de México",
    "Coahuila",
    "Colima",
    "Durango",
    "Estado de México",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "Michoacán",
    "Morelos",
    "Nayarit",
    "Nuevo León",
    "Oaxaca",
    "Puebla",
    "Querétaro",
    "Quintana Roo",
    "San Luis Potosí",
    "Sinaloa",
    "Sonora",
    "Tabasco",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz",
    "Yucatán",
    "Zacatecas",
]

NAME_TO_FIELD: dict[str, str | tuple[str, str]] = {
    "name": "places.displayName",
    "address": "places.formattedAddress",
    "phone": "places.internationalPhoneNumber",
    "opening_hours": (
        "places.regularOpeningHours",
        "places.regularSecondaryOpeningHours",
    ),
    "rating": ("places.rating",
                "places.userRatingCount"
    ),
    "reviews": "places.reviews",
    "website": "places.websiteUri",
    "coordinates": "places.location",
    "photos": "places.photos",
    "category": "places.types",
    "plus_code": "places.plusCode",
}

PLACES_URL = "https://places.googleapis.com/v1/places:searchText"
